### ISSUE TITLE
Server returned an error about a "not non-negative" context size

### ISSUE THREAD

**Issue by XiaoningDing** [bd-iaas-us/autoSE#35]
(It's just a random code change to test if the tool can point out the problem)

xiaoningding@C02GM5A2Q05N cannyls-go % pwd
/Users/xiaoningding/src/cannyls-go

xiaoningding@C02GM5A2Q05N cannyls-go % git diff
```
diff --git a/storage/storage.go b/storage/storage.go
index bac392b..f4e4393 100644
--- a/storage/storage.go
+++ b/storage/storage.go
@@ -58,6 +58,9 @@ type StorageUsage struct {
 
 func OpenCannylsStorage(path string) (*Storage, error) {
        file, header, err := nvm.Open(path)
+       if header == nil {
+               return nil, err
+       }
        if err != nil {
                return nil, err
        }
```

xiaoningding@C02GM5A2Q05N cannyls-go % ailint --file-name storage/storage.go        
ERROR: {"message":"internal error: Calculated available context size -1707 was not non-negative."}

**Comment by XiaoningDing** [comment]
We will check if this still reproduces after we switch to the more powerful internal model.

**Comment by thesues** [comment]
![image](https://github.com/bd-iaas-us/autoSE/assets/475224/2f67cb29-6f8c-438d-b24e-9e1150333c74)

now ailint could find nvm.open's err is not checked.
